Config:
  Messages:
    Scoreboard-Toggle:
      'ON': '&fScoreboard turned &aON&f.'
      'OFF': '&fScoreboard turned &cOFF&f.'
  Animations:
    Rainbow-Delay: 10
    Title-Delay: 2
    Scroll-Text:
      Size: 12
      Space: 2
  Scoreboard-Refresh: 2
  Disabled-Worlds:
    - ExampleWorld
    - ExampleWorld2
  Scoreboard:
    Lobby:
      Lines:
        - '%blank%'
        - ' &7Name: #&f%playername%#'
        - ' &7Ping: &f%ping%'
        - ' &7Money: &f%money%€'
        - ' &7Time: &f%time%'
        - ' &7Day: &f%day%'
        - ' &7Location:'
        - ' &f%loc%'
        - ' &7Stats: #&fKills: %kills% - Deaths: %deaths% - Mob Kills: %mobkills% - Jumps: %jumps%#'
        - '%blank%'
        - ' &7RAM: &f%ram%'
        - ' &7Online: &f%online%&8/&f%maxplayers%'
        - ' &7News: #&fWelcome to the new &bReal&9Scoreboard&f! Now with scrolling text.   &fIf you like this plugin, give it a &65 star &frating!#'
        - '%blank%'
      Title:
        - '%rainbow%RealScoreBoard'
    flat:
      Lines:
        - '%blank%'
        - ' &7Hello, &f%playername%'
        - ' &fWelcome to the server!'
        - '%blank%'
        - ' &fYou are on: #&f%world%#'
        - '%blank%'
      Title:
        - '&aFlat &bWorld'
    world3:
      Lines:
        - '&8%rainbow%&l&m------------------------'
        - '&7Third scoreboard'
        - '%rainbow%&l&m------------------------'
      Title:
        - '&6This is the Third scoreboard.'
Version: 2